services:
  ticktick-mcp:
    build: .
    ports:
      - "3434:3434"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    # Default command is already defined in Dockerfile
    # Uncomment to override:
    # command: uv run -m ticktick_mcp.cli run --transport sse --host 0.0.0.0 --port 3434